//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDesarrWebU2.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipopago
    {
        public int idtp { get; set; }
        public string numtarjtp { get; set; }
        public Nullable<int> idfact { get; set; }
    
        public virtual factura factura { get; set; }
    }
}
